---
title: "DO NPC transcriptome"
author: "Selcan Aydin"
date: "`r Sys.Date()`"
format: 
  html:
      embed-resources: true
      standalone: true
include-in-header:
  - text: |
      <style>
      .panel-tabset > .nav-tabs,
      .panel-tabset > .tab-content {
        border: none;
      }
      </style>
code-fold: true
toc: true
toc-depth: 5
toc-expand: true
editor: 
  markdown: 
    wrap: sentence
---

```{r setup}
#| warning: false  
#| message: false

options(stringsAsFactors = F)
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(progress=FALSE)

# # plotting
library(ggpubr)
library(igraph)
library(ggraph)
library(pheatmap)
library(cowplot)
library(GGally)
library(corrplot)
library(eulerr) 

# annotations + general genomic things
#library(biomaRt)
library(GenomicRanges)

# analysis
library(Hmisc) # rcorr
library(gprofiler2)
# set gprofiler version
set_base_url("https://biit.cs.ut.ee/gprofiler_archive3/e107_eg54_p17/")

library(sva)
library(WebGestaltR)
library(WGCNA)
library(GSVA)
library(GO.db)
library(rstatix)

#data handling and display
library(DT)
library(readxl)
library(tidyverse)
select <- dplyr::select # I am adding this explicitly
rename <- dplyr::rename # I am adding this explicitly

# setting path
library(here)

```


```{r load_data}

```


# Variation in the DO NPC transcriptome

# Covariation in the DO ESC and NPC transcript abundance

# Differential expression analysis


